apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: kwmoisfox-python 
  janus-idp.io/tekton: kwmoisfox-python
  backstage.io/kubernetes-id: kwmoisfox-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: kwmoisfox-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  